-- ===================================================================
-- SKRIP DATABASE SUPABASE: PORTAL SMP NEGERI MUARA SIRAM
-- Tabel: materi_pelajaran & jadwal_pelajaran
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> Run
-- ===================================================================

-- 1. TABEL MATERI PELAJARAN (Filter berdasarkan Kelas & Pertemuan)
CREATE TABLE IF NOT EXISTS materi_pelajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kelas VARCHAR(20) NOT NULL,          -- 'Kelas VII', 'Kelas VIII', 'Kelas IX'
    mapel VARCHAR(100) NOT NULL,         -- Mata Pelajaran (misal: 'Informatika', 'Matematika')
    pertemuan INT NOT NULL DEFAULT 1,    -- Nomor Pertemuan: 1, 2, 3, dst.
    judul VARCHAR(255) NOT NULL,         -- Judul Materi Pokok
    deskripsi TEXT,                      -- Ringkasan materi / instruksi belajar
    file_url TEXT NOT NULL,              -- Link file (PDF/Doc/Gambar/Link Supabase Storage)
    file_type VARCHAR(50) DEFAULT 'file',-- 'pdf', 'image', 'doc', 'link'
    nama_guru VARCHAR(100),              -- Guru Pengampu
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kebijakan Akses (RLS) materi_pelajaran
ALTER TABLE materi_pelajaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Insert Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Update Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Delete Materi" ON materi_pelajaran;

CREATE POLICY "Public Read Materi" ON materi_pelajaran FOR SELECT USING (true);
CREATE POLICY "Public Insert Materi" ON materi_pelajaran FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Materi" ON materi_pelajaran FOR UPDATE USING (true);
CREATE POLICY "Public Delete Materi" ON materi_pelajaran FOR DELETE USING (true);


-- 2. TABEL JADWAL PELAJARAN (Filter berdasarkan Kelas & Hari)
CREATE TABLE IF NOT EXISTS jadwal_pelajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kelas VARCHAR(20) NOT NULL,          -- 'Kelas VII', 'Kelas VIII', 'Kelas IX'
    hari VARCHAR(20) NOT NULL,           -- 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'
    jam_ke INT NOT NULL,                 -- Urutan jam: 1, 2, 3, dst.
    waktu VARCHAR(50) NOT NULL,          -- Format: '07.30 - 08.50'
    mapel VARCHAR(100) NOT NULL,         -- Nama Mata Pelajaran
    guru VARCHAR(100) NOT NULL,          -- Guru Pengampu
    ruang VARCHAR(50) DEFAULT 'Kelas',   -- Ruang Belajar / Laboratorium
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kebijakan Akses (RLS) jadwal_pelajaran
ALTER TABLE jadwal_pelajaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Insert Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Update Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Delete Jadwal" ON jadwal_pelajaran;

CREATE POLICY "Public Read Jadwal" ON jadwal_pelajaran FOR SELECT USING (true);
CREATE POLICY "Public Insert Jadwal" ON jadwal_pelajaran FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Jadwal" ON jadwal_pelajaran FOR UPDATE USING (true);
CREATE POLICY "Public Delete Jadwal" ON jadwal_pelajaran FOR DELETE USING (true);

-- 3. DATA AWAL JADWAL PELAJARAN (STANDAR SMP)
INSERT INTO jadwal_pelajaran (kelas, hari, jam_ke, waktu, mapel, guru, ruang) VALUES
-- KELAS VII
('Kelas VII', 'Senin', 1, '07.00 - 07.45', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas VII', 'Senin', 2, '07.45 - 09.05', 'Bahasa Indonesia', 'Ibu Rahmawati, S.Pd', 'Kelas VII'),
('Kelas VII', 'Senin', 3, '09.25 - 10.45', 'Matematika', 'Bpk. Ahmad, S.Pd', 'Kelas VII'),
('Kelas VII', 'Senin', 4, '10.45 - 12.05', 'Informatika', 'Bpk. Hendra, S.Kom', 'Lab Komputer'),

('Kelas VII', 'Selasa', 1, '07.30 - 08.50', 'IPA Terpadu', 'Ibu Nurul, M.Pd', 'Lab IPA'),
('Kelas VII', 'Selasa', 2, '09.10 - 10.30', 'Bahasa Inggris', 'Bpk. David, M.Pd', 'Kelas VII'),
('Kelas VII', 'Selasa', 3, '10.30 - 11.50', 'Pendidikan Agama', 'Bpk. H. Syarif, S.Ag', 'Kelas VII'),

('Kelas VII', 'Rabu', 1, '07.30 - 08.50', 'Pendidikan Pancasila', 'Ibu Sri Wahyuni, S.Pd', 'Kelas VII'),
('Kelas VII', 'Rabu', 2, '09.10 - 10.30', 'IPS Terpadu', 'Bpk. Joko, S.Pd', 'Kelas VII'),
('Kelas VII', 'Rabu', 3, '10.30 - 11.50', 'Seni Budaya', 'Ibu Rina, S.Sn', 'Kelas VII'),

('Kelas VII', 'Kamis', 1, '07.30 - 08.50', 'PJOK / Penjaskes', 'Bpk. Budi Santoso, S.Pd', 'Lapangan'),
('Kelas VII', 'Kamis', 2, '09.10 - 10.30', 'Prakarya', 'Ibu Dewi, S.Pd', 'Kelas VII'),
('Kelas VII', 'Kamis', 3, '10.30 - 11.50', 'Bahasa Daerah', 'Ibu Siti, S.Pd', 'Kelas VII'),

('Kelas VII', 'Jumat', 1, '07.30 - 08.15', 'Senam Pagi & Literasi', 'Wali Kelas', 'Lapangan'),
('Kelas VII', 'Jumat', 2, '08.15 - 09.35', 'Bimbingan Konseling', 'Ibu Fitri, S.Psi', 'Ruang BK'),
('Kelas VII', 'Jumat', 3, '09.35 - 10.30', 'Pengembangan Diri / Ekstra', 'Pembina Ekstra', 'Kelas VII'),

-- KELAS VIII
('Kelas VIII', 'Senin', 1, '07.00 - 07.45', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas VIII', 'Senin', 2, '07.45 - 09.05', 'Matematika', 'Bpk. Ahmad, S.Pd', 'Kelas VIII'),
('Kelas VIII', 'Senin', 3, '09.25 - 10.45', 'Bahasa Indonesia', 'Ibu Rahmawati, S.Pd', 'Kelas VIII'),
('Kelas VIII', 'Senin', 4, '10.45 - 12.05', 'IPA Terpadu', 'Ibu Nurul, M.Pd', 'Lab IPA'),

('Kelas VIII', 'Selasa', 1, '07.30 - 08.50', 'Informatika', 'Bpk. Hendra, S.Kom', 'Lab Komputer'),
('Kelas VIII', 'Selasa', 2, '09.10 - 10.30', 'Pendidikan Agama', 'Bpk. H. Syarif, S.Ag', 'Kelas VIII'),
('Kelas VIII', 'Selasa', 3, '10.30 - 11.50', 'Bahasa Inggris', 'Bpk. David, M.Pd', 'Kelas VIII'),

('Kelas VIII', 'Rabu', 1, '07.30 - 08.50', 'IPS Terpadu', 'Bpk. Joko, S.Pd', 'Kelas VIII'),
('Kelas VIII', 'Rabu', 2, '09.10 - 10.30', 'Pendidikan Pancasila', 'Ibu Sri Wahyuni, S.Pd', 'Kelas VIII'),
('Kelas VIII', 'Rabu', 3, '10.30 - 11.50', 'PJOK / Penjaskes', 'Bpk. Budi Santoso, S.Pd', 'Lapangan'),

('Kelas VIII', 'Kamis', 1, '07.30 - 08.50', 'Seni Budaya', 'Ibu Rina, S.Sn', 'Kelas VIII'),
('Kelas VIII', 'Kamis', 2, '09.10 - 10.30', 'Prakarya', 'Ibu Dewi, S.Pd', 'Kelas VIII'),
('Kelas VIII', 'Kamis', 3, '10.30 - 11.50', 'Bahasa Daerah', 'Ibu Siti, S.Pd', 'Kelas VIII'),

('Kelas VIII', 'Jumat', 1, '07.30 - 08.15', 'Senam Pagi & Literasi', 'Wali Kelas', 'Lapangan'),
('Kelas VIII', 'Jumat', 2, '08.15 - 09.35', 'Informatika Mandiri', 'Bpk. Hendra, S.Kom', 'Lab Komputer'),

-- KELAS IX
('Kelas IX', 'Senin', 1, '07.00 - 07.45', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas IX', 'Senin', 2, '07.45 - 09.05', 'IPA Terpadu', 'Ibu Nurul, M.Pd', 'Lab IPA'),
('Kelas IX', 'Senin', 3, '09.25 - 10.45', 'Bahasa Inggris', 'Bpk. David, M.Pd', 'Kelas IX'),
('Kelas IX', 'Senin', 4, '10.45 - 12.05', 'Matematika', 'Bpk. Ahmad, S.Pd', 'Kelas IX'),

('Kelas IX', 'Selasa', 1, '07.30 - 08.50', 'Bahasa Indonesia', 'Ibu Rahmawati, S.Pd', 'Kelas IX'),
('Kelas IX', 'Selasa', 2, '09.10 - 10.30', 'Informatika', 'Bpk. Hendra, S.Kom', 'Lab Komputer'),
('Kelas IX', 'Selasa', 3, '10.30 - 11.50', 'IPS Terpadu', 'Bpk. Joko, S.Pd', 'Kelas IX'),

('Kelas IX', 'Rabu', 1, '07.30 - 08.50', 'Pendidikan Agama', 'Bpk. H. Syarif, S.Ag', 'Kelas IX'),
('Kelas IX', 'Rabu', 2, '09.10 - 10.30', 'PJOK / Penjaskes', 'Bpk. Budi Santoso, S.Pd', 'Lapangan'),
('Kelas IX', 'Rabu', 3, '10.30 - 11.50', 'Pendidikan Pancasila', 'Ibu Sri Wahyuni, S.Pd', 'Kelas IX'),

('Kelas IX', 'Kamis', 1, '07.30 - 08.50', 'Prakarya', 'Ibu Dewi, S.Pd', 'Kelas IX'),
('Kelas IX', 'Kamis', 2, '09.10 - 10.30', 'Seni Budaya', 'Ibu Rina, S.Sn', 'Kelas IX'),
('Kelas IX', 'Kamis', 3, '10.30 - 11.50', 'Bahasa Daerah', 'Ibu Siti, S.Pd', 'Kelas IX'),

('Kelas IX', 'Jumat', 1, '07.30 - 08.15', 'Senam Pagi & Pembinaan Rohani', 'Wali Kelas', 'Lapangan'),
('Kelas IX', 'Jumat', 2, '08.15 - 09.35', 'Bimbingan Konseling / Ujian', 'Ibu Fitri, S.Psi', 'Kelas IX');

-- 4. CONTOH DATA AWAL MATERI PELAJARAN
INSERT INTO materi_pelajaran (kelas, mapel, pertemuan, judul, deskripsi, file_url, file_type, nama_guru) VALUES
('Kelas VII', 'Informatika', 1, 'Pengenalan Perangkat Keras Komputer (Hardware)', 'Mempelajari komponen input, proses, output, dan penyimpanan pada komputer.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VII', 'Informatika', 2, 'Sistem Operasi dan Pengelolaan File', 'Memahami sistem operasi Windows dan cara manajemen folder tugas sekolah.', 'https://drive.google.com', 'doc', 'Bpk. Hendra, S.Kom'),
('Kelas VII', 'Informatika', 3, 'Internet Aman dan Etika Berkomunikasi Digital', 'Panduan menggunakan internet sehat, media sosial, dan etika digital.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VIII', 'Informatika', 1, 'Jaringan Komputer dan Internet (Topologi Jaringan)', 'Mengenal konsep LAN, WAN, IP Address, dan topologi jaringan lokal sekolah.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VIII', 'Informatika', 2, 'Pengolahan Angka (Spreadsheet & Rumus Excel)', 'Praktik rumus SUM, AVERAGE, IF, dan pembuatan tabel rekapitulasi data.', 'https://drive.google.com', 'doc', 'Bpk. Hendra, S.Kom'),
('Kelas IX', 'Informatika', 1, 'Berpikir Komputasional dan Pemrograman Dasar', 'Memahami algoritma, flowchart, dan logika pemecahan masalah komputasi.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom');
