-- ===================================================================
-- SKRIP DATABASE SUPABASE: PORTAL SMP NEGERI 5 MUARA SIRAM
-- Tabel: materi_pelajaran & jadwal_pelajaran
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> Run
-- ===================================================================

-- 1. TABEL MATERI PELAJARAN (Filter berdasarkan Kelas & Pertemuan)
CREATE TABLE IF NOT EXISTS materi_pelajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kelas VARCHAR(20) NOT NULL,          -- 'Kelas VII', 'Kelas VIII', 'Kelas IX'
    mapel VARCHAR(100) NOT NULL,         -- Mata Pelajaran (misal: 'Informatika', 'Matematika')
    pertemuan INT NOT NULL DEFAULT 1,    -- Nomor Pertemuan: 1, 2, 3, dst.
    judul VARCHAR(255) NOT NULL,         -- Judul Materi Pokok
    deskripsi TEXT,                      -- Ringkasan materi / instruksi belajar
    file_url TEXT NOT NULL,              -- Link file (PDF/Doc/Gambar/Link Supabase Storage)
    file_type VARCHAR(50) DEFAULT 'file',-- 'pdf', 'image', 'doc', 'link'
    nama_guru VARCHAR(100),              -- Guru Pengampu
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kebijakan Akses (RLS) materi_pelajaran
ALTER TABLE materi_pelajaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Insert Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Update Materi" ON materi_pelajaran;
DROP POLICY IF EXISTS "Public Delete Materi" ON materi_pelajaran;

CREATE POLICY "Public Read Materi" ON materi_pelajaran FOR SELECT USING (true);
CREATE POLICY "Public Insert Materi" ON materi_pelajaran FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Materi" ON materi_pelajaran FOR UPDATE USING (true);
CREATE POLICY "Public Delete Materi" ON materi_pelajaran FOR DELETE USING (true);


-- 2. TABEL JADWAL PELAJARAN (Filter berdasarkan Kelas & Hari)
CREATE TABLE IF NOT EXISTS jadwal_pelajaran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kelas VARCHAR(20) NOT NULL,          -- 'Kelas VII', 'Kelas VIII', 'Kelas IX'
    hari VARCHAR(20) NOT NULL,           -- 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'
    jam_ke INT NOT NULL,                 -- Urutan jam: 1, 2, 3, dst.
    waktu VARCHAR(50) NOT NULL,          -- Format: '07.30 - 08.50'
    mapel VARCHAR(100) NOT NULL,         -- Nama Mata Pelajaran
    guru VARCHAR(100) NOT NULL,          -- Guru Pengampu
    ruang VARCHAR(50) DEFAULT 'Kelas',   -- Ruang Belajar / Laboratorium
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kebijakan Akses (RLS) jadwal_pelajaran
ALTER TABLE jadwal_pelajaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Insert Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Update Jadwal" ON jadwal_pelajaran;
DROP POLICY IF EXISTS "Public Delete Jadwal" ON jadwal_pelajaran;

CREATE POLICY "Public Read Jadwal" ON jadwal_pelajaran FOR SELECT USING (true);
CREATE POLICY "Public Insert Jadwal" ON jadwal_pelajaran FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Jadwal" ON jadwal_pelajaran FOR UPDATE USING (true);
CREATE POLICY "Public Delete Jadwal" ON jadwal_pelajaran FOR DELETE USING (true);

-- 3. DATA RESMI JADWAL PELAJARAN (SMPN 5 MUARA SIRAM T.P 2026/2027)
TRUNCATE TABLE jadwal_pelajaran;
INSERT INTO jadwal_pelajaran (kelas, hari, jam_ke, waktu, mapel, guru, ruang) VALUES
-- KELAS VII
('Kelas VII', 'Senin', 1, '07.30 - 08.10', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas VII', 'Senin', 2, '08.10 - 09.30', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Senin', 3, '09.30 - 10.10', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Senin', 5, '10.40 - 12.00', 'PPKn', 'Hetti, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Senin', 8, '12.00 - 13.20', 'Prakarya', 'Dwi Oktaviani S, S.Pd.,Gr.', 'Kelas VII'),

('Kelas VII', 'Selasa', 1, '07.30 - 08.50', 'PJOK', 'Hamdani, S.Pd.,Gr.', 'Lapangan'),
('Kelas VII', 'Selasa', 3, '08.50 - 10.10', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Selasa', 5, '10.40 - 12.00', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Selasa', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VII'),

('Kelas VII', 'Rabu', 1, '07.30 - 08.50', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Rabu', 3, '08.50 - 10.10', 'Pendidikan Agama (PAI/PAK)', 'M. Dony Wardhana / Deyby Taniowas', 'Kelas VII'),
('Kelas VII', 'Rabu', 5, '10.40 - 12.00', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas VII', 'Rabu', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VII'),

('Kelas VII', 'Kamis', 1, '07.30 - 09.30', 'Bahasa Inggris', 'M. Ilham, S.Pd.,Gr.', 'Kelas VII'),
('Kelas VII', 'Kamis', 3, '09.30 - 10.10', 'IPS', 'Yanti, S.Pd.', 'Kelas VII'),
('Kelas VII', 'Kamis', 5, '10.40 - 12.00', 'IPS', 'Yanti, S.Pd.', 'Kelas VII'),
('Kelas VII', 'Kamis', 8, '12.00 - 13.20', 'Jam Guru Wali', 'Wali Kelas VII', 'Kelas VII'),

('Kelas VII', 'Jumat', 1, '07.30 - 08.10', 'Senam Pagi Bersama', 'Guru PJOK / Wali Kelas', 'Lapangan'),
('Kelas VII', 'Jumat', 2, '08.10 - 09.30', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VII'),
('Kelas VII', 'Jumat', 4, '09.50 - 11.10', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VII'),

('Kelas VII', 'Sabtu', 1, '07.30 - 08.50', 'Pembinaan Keagamaan', 'Guru Keagamaan', 'Kelas VII'),
('Kelas VII', 'Sabtu', 3, '08.50 - 10.10', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas VII', 'Sabtu', 5, '10.40 - 12.00', 'TIK / Informatika', 'Hamdani, S.Pd.,Gr.', 'Lab Komputer'),

-- KELAS VIII
('Kelas VIII', 'Senin', 1, '07.30 - 08.10', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas VIII', 'Senin', 2, '08.10 - 10.10', 'IPS', 'Yanti, S.Pd.', 'Kelas VIII'),
('Kelas VIII', 'Senin', 5, '10.40 - 11.20', 'Bahasa Inggris', 'M. Ilham, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Senin', 6, '11.20 - 13.20', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas VIII'),

('Kelas VIII', 'Selasa', 1, '07.30 - 08.50', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Selasa', 3, '08.50 - 10.10', 'Pendidikan Agama (PAI/PAK)', 'M. Dony Wardhana / Deyby Taniowas', 'Kelas VIII'),
('Kelas VIII', 'Selasa', 5, '10.40 - 12.00', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas VIII', 'Selasa', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VIII'),

('Kelas VIII', 'Rabu', 1, '07.30 - 08.50', 'PJOK', 'Hamdani, S.Pd.,Gr.', 'Lapangan'),
('Kelas VIII', 'Rabu', 3, '08.50 - 10.10', 'PPKn', 'Hetti, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Rabu', 5, '10.40 - 12.00', 'Prakarya', 'Dwi Oktaviani S, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Rabu', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VIII'),

('Kelas VIII', 'Kamis', 1, '07.30 - 08.50', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Kamis', 3, '08.50 - 10.10', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas VIII', 'Kamis', 5, '10.40 - 12.00', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas VIII'),
('Kelas VIII', 'Kamis', 8, '12.00 - 13.20', 'Jam Guru Wali', 'Wali Kelas VIII', 'Kelas VIII'),

('Kelas VIII', 'Jumat', 1, '07.30 - 08.10', 'Senam Pagi Bersama', 'Guru PJOK / Wali Kelas', 'Lapangan'),
('Kelas VIII', 'Jumat', 2, '08.10 - 09.30', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VIII'),
('Kelas VIII', 'Jumat', 4, '09.50 - 11.10', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas VIII'),

('Kelas VIII', 'Sabtu', 1, '07.30 - 08.50', 'Pembinaan Keagamaan', 'Guru Keagamaan', 'Kelas VIII'),
('Kelas VIII', 'Sabtu', 3, '08.50 - 10.10', 'TIK / Informatika', 'Deyby Taniowas, S.Pd.K.', 'Lab Komputer'),
('Kelas VIII', 'Sabtu', 5, '10.40 - 12.00', 'Bahasa Inggris', 'M. Ilham, S.Pd.,Gr.', 'Kelas VIII'),

-- KELAS IX
('Kelas IX', 'Senin', 1, '07.30 - 08.10', 'Upacara Bendera', 'Pembina Upacara', 'Lapangan'),
('Kelas IX', 'Senin', 2, '08.10 - 10.10', 'Bahasa Inggris', 'M. Ilham, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Senin', 5, '10.40 - 12.00', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas IX', 'Senin', 8, '12.00 - 13.20', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas IX'),

('Kelas IX', 'Selasa', 1, '07.30 - 08.50', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Selasa', 3, '08.50 - 10.10', 'IPA', 'Amanda Kartika, S.Pd.,Gr.', 'Lab IPA'),
('Kelas IX', 'Selasa', 5, '10.40 - 12.00', 'PPKn', 'Hetti, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Selasa', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas IX'),

('Kelas IX', 'Rabu', 1, '07.30 - 09.30', 'Bahasa Indonesia', 'Roi Martin, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Rabu', 3, '09.30 - 10.10', 'IPS', 'Yanti, S.Pd.', 'Kelas IX'),
('Kelas IX', 'Rabu', 5, '10.40 - 12.00', 'IPS', 'Yanti, S.Pd.', 'Kelas IX'),
('Kelas IX', 'Rabu', 8, '12.00 - 13.20', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas IX'),

('Kelas IX', 'Kamis', 1, '07.30 - 08.50', 'PJOK', 'Hamdani, S.Pd.,Gr.', 'Lapangan'),
('Kelas IX', 'Kamis', 3, '08.50 - 10.10', 'Matematika', 'Supianto, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Kamis', 5, '10.40 - 12.00', 'Pendidikan Agama (PAI/PAK)', 'M. Dony Wardhana / Deyby Taniowas', 'Kelas IX'),
('Kelas IX', 'Kamis', 8, '12.00 - 13.20', 'Jam Guru Wali', 'Wali Kelas IX', 'Kelas IX'),

('Kelas IX', 'Jumat', 1, '07.30 - 08.10', 'Senam Pagi Bersama', 'Guru PJOK / Wali Kelas', 'Lapangan'),
('Kelas IX', 'Jumat', 2, '08.10 - 09.30', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas IX'),
('Kelas IX', 'Jumat', 4, '09.50 - 11.10', 'Ko-Kurikuler (KOKUR)', 'Guru Pembina', 'Kelas IX'),

('Kelas IX', 'Sabtu', 1, '07.30 - 08.50', 'Pembinaan Keagamaan', 'Guru Keagamaan', 'Kelas IX'),
('Kelas IX', 'Sabtu', 3, '08.50 - 10.10', 'Prakarya', 'Dwi Oktaviani S, S.Pd.,Gr.', 'Kelas IX'),
('Kelas IX', 'Sabtu', 5, '10.40 - 12.00', 'TIK / Informatika', 'Dwi Oktaviani S, S.Pd.,Gr.', 'Lab Komputer');

-- 4. CONTOH DATA AWAL MATERI PELAJARAN
INSERT INTO materi_pelajaran (kelas, mapel, pertemuan, judul, deskripsi, file_url, file_type, nama_guru) VALUES
('Kelas VII', 'Informatika', 1, 'Pengenalan Perangkat Keras Komputer (Hardware)', 'Mempelajari komponen input, proses, output, dan penyimpanan pada komputer.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VII', 'Informatika', 2, 'Sistem Operasi dan Pengelolaan File', 'Memahami sistem operasi Windows dan cara manajemen folder tugas sekolah.', 'https://drive.google.com', 'doc', 'Bpk. Hendra, S.Kom'),
('Kelas VII', 'Informatika', 3, 'Internet Aman dan Etika Berkomunikasi Digital', 'Panduan menggunakan internet sehat, media sosial, dan etika digital.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VIII', 'Informatika', 1, 'Jaringan Komputer dan Internet (Topologi Jaringan)', 'Mengenal konsep LAN, WAN, IP Address, dan topologi jaringan lokal sekolah.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom'),
('Kelas VIII', 'Informatika', 2, 'Pengolahan Angka (Spreadsheet & Rumus Excel)', 'Praktik rumus SUM, AVERAGE, IF, dan pembuatan tabel rekapitulasi data.', 'https://drive.google.com', 'doc', 'Bpk. Hendra, S.Kom'),
('Kelas IX', 'Informatika', 1, 'Berpikir Komputasional dan Pemrograman Dasar', 'Memahami algoritma, flowchart, dan logika pemecahan masalah komputasi.', 'https://drive.google.com', 'pdf', 'Bpk. Hendra, S.Kom');
